# Generated by Django 5.2.5 on 2025-11-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
